name: Loop Test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  ping-website:
    runs-on: ubuntu-latest
   

    steps:
      - name: Start infinite request loop
        run: |
          while true; do
            echo "Pinging https://devstudio-ai.vercel.app/ at $(date)"
            curl -s -o /dev/null -w "%{http_code}\n" https://devstudio-ai.vercel.app/
           
          done
